### PR TITLE
coname's VRF implementation (self-contained)

### PR DESCRIPTION
**Pull request by Liamsi**
This is an (almost) unmodified version of the coname's authors VRF implementation. As soon as this is merged I could integrate it into the existing code base.

### CODE REVIEW

**Comment by Liamsi** [comment]
Related to issue #5

**Comment by Liamsi** [comment]
We might want to put it or add it to the internal coname package instead?

If you wonder why we have yet another `ed25519`package: agl's implementation of the elligator map needs some methods of the packages which are internal in the original golang repo: https://github.com/golang/crypto/tree/master/ed25519/internal/edwards25519  compare to https://github.com/coniks-sys/libmerkleprefixtree-go/blob/vrf_impl_coname_agl/crypto/ed25519

**Comment by c633** [comment]
About the `ed25519.go` source file, why don't we use current source code in the official `crypto/ed25519` pkg?

**Comment by Liamsi** [comment]
> About the ed25519.go source file, why don't we use current source code in the official crypto/ed25519 pkg? 

Yes, maybe it's worth it to investigate the changes and use the official golang version. If I rememeber correctly I already started that and it didn't work out fine (can't remember the reason though)

**Comment by Liamsi** [comment]
No, seem to work fine. Thanks @c633

**Comment by masomel** [comment]
@Liamsi is this ready to be merged?

**Comment by Liamsi** [comment]
> @Liamsi is this ready to be merged?

From my side yes.

**Comment by masomel** [comment]
Cool. I'll handle the merge.

**Comment by masomel** [comment]
@Liamsi One more question: is the vrf subpackage in crypto/vrf copyrighted to the coname authors?

**Comment by Liamsi** [comment]
As far as I understood it, yes it is copyrighted by the coname authors as it is part of coname repo.
But some of the files are actually copies of golang's internal edwards25519 package (see https://github.com/coniks-sys/libmerkleprefixtree-go/pull/12#issuecomment-229041412). 
But I'm also not too familiar with copyright though. While talking to Andres and Daniel they definitely/endorsed the idea of using their implementation in our project. But I think we still would need to mention that in the license.

**Comment by masomel** [comment]
Ok. I already included a notice about the ed25519 subpackage in our license, so we should be fine on that front. I'll add a note about the vrf subpackage in a similar fashion. Thanks!

**Comment by Liamsi** [comment]
Thank you too for taking care of that!

**Pull request merged**
